Add timestamps to actions protocol binding - closes #101
w3c/wot-profile pull request #127
Opened 2021-11-10 16:14 UTC by benfrancis

2021-11-15 14:34 UTC, mlagally commented
@benfrancis 
This looks good, a few comments:
We have to change our mindset wrt. optionality for the profile. Whereas the TD itself makes almost everything optional to enable description of brown field devices, the profile should contain reasonable normative guarantees.
Therefore I suggest to make these timestamps mandatory.

2021-11-15 14:35 UTC, mlagally commented
One more thing - Suggest to combine timeFailed and timeSucceeded into a single timestamp: name could be something like timeFinished, timeTerminated, ....

2021-11-16 11:27 UTC, benfrancis commented
> I suggest to make these timestamps mandatory.
...
> Suggest to combine timeFailed and timeSucceeded into a single timestamp: name could be something like timeFinished, timeTerminated

@mlagally Please see the comments I made in #101 and https://github.com/w3c/wot-profile/issues/101#issuecomment-966217434 regarding both of these points last week.

> We have to change our mindset wrt. optionality for the profile. Whereas the TD itself makes almost everything optional to enable description of brown field devices, the profile should contain reasonable normative guarantees.

Whilst I agree that Profiles should be more prescriptive than the Thing Description specification in general, in many cases I think it's sufficient to say that Consumers MUST support a feature and Producers MAY use it.

2021-11-24 15:43 UTC, mlagally commented
> Whilst I agree that Profiles should be more prescriptive than the Thing Description specification in general, in many cases I think it's sufficient to say that Consumers MUST support a feature and Producers MAY use it.

I think this statement is problematic and may hinder adoption.
The profile is a contract between consumers and things and should minimize implementation complexity on both components.

2021-11-25 09:38 UTC, mlagally requested changes

2021-11-25 09:38 UTC, mlagally commented on index.html
> +                  A timestamp indicating the time at which the Action failed to
Please consider to eliminate timeFailed. 
This information should be conveyed in the action response.

2021-11-25 10:00 UTC, benfrancis commented
Regarding the feedback here and in #101...

One of the reasons I originally made the timestamps optional was because you said that some devices may not be able to generate timestamps because they don't have a clock. I therefore also did the same for events.

However, I have now:
1. Combined `timeCompleted` and `timeFailed` into `timeEnded` (`timeFinished` sounds too much like completed and `timeTerminated` sounds too much like it failed)
2. Made `timeRequested` mandatory

A couple of additional points:
1. I considered renaming `timeRequested` to `timeStarted` to better match `timeEnded` but then I realised that changes the meaning. There's an ambiguity between time requested and time started, which may not be the same if the Thing uses an action queue. That is may be a separate issue.
2. I was going to make `timeEnded` mandatory too but that doesn't really make sense for an action which hasn't yet ended!

2022-03-23 10:16 UTC, mlagally approved these changes

2022-03-23 17:05 UTC, benfrancis commented on index.html
> +                  the request to execute the action, in ISO format [[ISO8601-1]].
I've added a reference to the additional constraints in the datetime section.

2022-03-23 17:08 UTC, benfrancis commented on index.html
> +                  successfully completed executing the action, or failed to
The `status` member would be set to `failed`.

2022-03-24 14:47 UTC, mlagally approved these changes

2022-03-30 11:56 UTC, mlagally commented
Profile call on March 30th:

There are devices with no RTC, it is hard to have a time value on them.
Consider to define a "duration" instead.
Precision of the value is also pontially an interoperability issue.
Need to more carefully consider use cases - is a sequence number and elapsed time sufficient for timeouts?

2022-04-13 16:40 UTC, benfrancis commented
> My suggestion:
> 
> * Revert `timeRequested` to being optional
> * Provide implementation guidance to say that Consumers should not assume that the clock of a Thing is set correctly and should therefore `timeEnded` as being relative to `timeRequested`, but not necessarily relative to the clock of the Consumer or the clocks of other Things or other Consumers.

I've pushed a commit which implements these changes. Please let me know what you think.

2022-05-11 11:49 UTC, merged