event-payload-format
w3c/wot-profile pull request #150
Opened 2021-12-01 07:27 UTC by mlagally

Strucutred event format that ensures interoperability of event payloads with the cloud events specification.
Additional event bindings, such as for observable properties and bindings to other HTTP/JSON based event subprotocols should use the same format to ensure interoperability.

2021-12-01 11:26 UTC, benfrancis requested changes
Hopefully it should come as no surprise to you that I don't approve of this change, for all the reasons already discussed in #100, #107, #126 and #134.

I am baffled as to why you continue to pursue this when it's clear that the consensus of the group so far is that it's not a good idea. There is a far simpler solution to the timestamp requirement proposed in #119 which only requires a one line change to the specification and much simpler data schemas and event payloads.

I have already implemented the current event protocol binding defined in the specification in WebThings Gateway and another Krellian product and I have no intention of changing them to adopt this unnecessarily complicated and over-engineered solution. I'm afraid you will need to find two other implementations willing to adopt this.

2022-04-06 12:15 UTC, egekorkan commented
If we want to align with cloud events, we should simply have a binding template for it and ideally some keyword like `subprotocol` to indicate the alignment in TDs. A profile can prescribe that this subprotocol must be used. The metadata around the protocol should not be put into the TDs, it would be bad practice from our side. 

To better illustrate my point with an analogy, it would be saying that the payload in a profile X should contain the data schema of the corresponding affordance.

2022-04-07 11:21 UTC, mlagally commented
@egekorkan 
Defining a subprotocol and a binding template for an event payload looks to me as a significant overhead to achieve only a simple goal, i.e. having a structured payload that some other cloud systems are already using.

I think it is appropriate to define the payload scheme as part of the event binding.

2022-04-07 12:28 UTC, egekorkan commented
> Defining a subprotocol and a binding template for an event payload looks to me as a significant overhead to achieve only a simple goal, i.e. having a structured payload that some other cloud systems are already using.

> I think it is appropriate to define the payload scheme as part of the event binding.

I agree with this. However, I strongly object to proposing cloud events for a WoT green field scenario. There should be a binding for cloud events anyway given the fact that you are saying it is heavily used. If we are the WoT standardization group and are proposing a new binding (this is a binding by the way since you are using an existing "standard") for people to implement in a given profile that is about WoT, we should leverage the existing technologies we have in WoT, namely the TD. 

If you write an example TD for this, I can better illustrate why this is a bad design choice.

2022-05-11 11:34 UTC, closed without merging