Cleanup core with baseline
w3c/wot-profile pull request #203
Opened 2022-05-17 14:14 UTC by mlagally

2022-05-17 21:00 UTC, benfrancis requested changes
Whilst I welcome the slight reduction in constraints, in my view these changes do not go far enough to address concerns with this section of the specification.

Please see my comments in https://github.com/w3c/wot-profile/issues/10#issuecomment-1129296959 where I suggest a more significant re-working of this section to remove unnecessary constraints and focus on the agreed requirements of the specification.

Examples:
- There is no need for title, description, base, id or version to be mandatory anywhere
- There is no need to constrain id to be a URN rather than anyURI
- There is no need to arbitrarily constrain the length of the title (or any) member
- There is no need to require arrays where a simple string would suffice
- There is no need to constrain the types of enums
- The recommendation to use an empty string for undefined values is undesirable
- Requirements about email addresses for developers and support are arbitrary and unnecessary
- There are valid use cases for properties without a type member (e.g. endpoints which resolve to a media file such as an image, audio or video file)
- There is no need to arbitrarily limit the depth of nested data structures
- There is no need to disallow the const keyword
- The constraint on the number of forms per interaction affordance and constraints on the values of op members are actively harmful to interoperability
- There's no need to disallow oneOf for properties
- Disallowing the use of uriVariables is actively harmful for interoperability
- There is no need to constrain the use of security fields and scopes

2022-05-20 06:18 UTC, mlagally commented
@benfrancis 
Thanks for your review and the list of your concerns.

This MR does not try to solve these problems, it's scope is just an alignment of language across the entire document.
I'm aware that we need to talk about these constraints and will address your concerns in one of the next profile calls, where I hope you can attend for a live discussion.

Following this clarification and alignment there will be other MRs.

2022-05-25 10:34 UTC, benfrancis reviewed
I'm sorry I'm unable to attend the WoT Profile meeting today.

I don't agree with the content of the content of the Baseline Information Model section, but given this PR is an improvement over what's currently there and will help to make this section less confusing as we continue the discussion, I would be OK with merging this PR if an Editor's Note is added to say the whole of section 6.2 is "at risk", perhaps linking to #10 for further discussion.

To be clear, we don't intend to implement the assertions in section 6.2 as currently written in WebThings.

2022-05-25 14:51 UTC, mlagally commented on index.html
> +                <td>value: "https://www.w3.org/2021/wot/profile/baseline-json-http11"</td>
done

2022-06-15 11:38 UTC, merged