Remove cloud events as message format for WebHooks
w3c/wot-profile pull request #251
Opened 2022-08-03 12:06 UTC by mlagally

2022-08-10 09:45 UTC, benfrancis approved these changes

2022-08-31 08:58 UTC, mlagally commented
I also updated the readme to reflect the recent name change, see #268

2022-08-31 10:59 UTC, benfrancis requested changes
The README changes seem unrelated to the WebHooks change, should that not be a separate PR?

2022-08-31 10:59 UTC, benfrancis commented on README.md
> +- In addition it defines a **Base Profile** of the Thing Description
There is no "Base Profile". There is an "HTTP Baseline Profile" which may be renamed to "HTTP Basic Profile" (#265), but it only uses HTTP (not "selected profiles" as written here).

2022-08-31 13:08 UTC, mlagally commented
Profile call on Aug 31.:
Agree to merge after removal of README.md changes

2022-08-31 13:08 UTC, merged