Rename HTTP Basline Profile to HTTP Basic Profile
w3c/wot-profile pull request #265
Opened 2022-08-24 10:38 UTC by benfrancis

This is a follow-up to #260 which proposes renaming the "HTTP Baseline Profile" to the "HTTP Basic Profile".

The reason for this is that I think after the re-structure in #260 there's potential for confusion between the terms "Baseline Profile" and "Common Constraints". The term "baseline" may imply that all other HTTP profiles all have to be built on top of the HTTP Baseline profile, which is not the case since they can also be used on their own. This addresses similar historical concerns about the the term "Core Profile" (#5, #21).

Note that this PR builds on #260, so please only review the third commit https://github.com/w3c/wot-profile/commit/96bf012250b97b097c29e8c4d60236a02a3b7468

2022-08-31 07:28 UTC, mlagally requested changes
The name change is an improvement and should be also done in the diagrams, both in profile and architecture.

However this MR also contains many unrelated changes, presumably you branched from a different branch. Can you please constrain the scope of this MR to the name change only.

2022-08-31 08:48 UTC, benfrancis commented
> However this MR also contains many unrelated changes, presumably you branched from a different branch. Can you please constrain the scope of this MR to the name change only.

Please read my comment from above:

>> Note that this PR builds on https://github.com/w3c/wot-profile/pull/260, so please only review the last commit https://github.com/w3c/wot-profile/commit/2bf7a552ca4d873c8bec806cae1918cc77c6cc77

This PR depends on #260 because the name change is largely motivated by the re-structure proposed in that PR. I can rebase this PR once if and when that one lands.

2022-08-31 14:28 UTC, benfrancis commented
> This PR depends on https://github.com/w3c/wot-profile/pull/260 because the name change is largely motivated by the re-structure proposed in that PR. I can rebase this PR once if and when that one lands.

This has now been done so this change can be reviewed on its own.

> should be also done in the diagrams, both in profile and architecture.

Hopefully this can be done as a follow-up as I can't find the source code of the diagrams concerned.

2022-08-31 15:18 UTC, mlagally commented
Thanks @benfrancis - I consider this ready to merge.
The diagram source is at: "images/Sequence Diagram - WebHook.puml"

You can use Plantuml to render the diagram.

2022-09-21 11:45 UTC, mlagally commented
Profile call on Sept 21.  - Agree to merge after the merge conflict has been resolved.
Please create another issue for the diagram(s)

2022-09-21 15:24 UTC, benfrancis commented
@mlagally I have resolved the merge conflict and I believe this is now ready to merge.

I have filed #290 to follow up on updating Figure 1.

2022-09-27 19:58 UTC, benfrancis commented
@mlagally I would be grateful if you could land this PR ASAP so that I have an opportunity to resolve any resulting merge conflicts in my other 9 PRs before tomorrow's meeting, so the same thing doesn't happen again. Thank you.

2022-09-28 09:30 UTC, mlagally approved these changes

2022-09-28 09:30 UTC, merged