Consolidate date-time references to RFC 3339 - closes #276
w3c/wot-profile pull request #287
Opened 2022-09-21 10:37 UTC by benfrancis

This PR addresses issue #276. It fixes inconsistent and broken references and changes all date-time constraints within the specification to refer to the Date Time section, which itself refers to RFC 3339.

I have changed the clarifying assertions in the Date Time section into a Note since they only repeat what it says in RFC 3339.

Apart from making the date format consistent throughout the specification, the only significant normative change is that timezones _are_ allowed in timestamps, but only by way of unambiguous numerical offsets as allowed by RFC 3339. This still helps remove ambiguity, but fixes the awkward situation where some RFC 3339 timestamps are valid and others are not, which should help simplify implementation.

2022-09-26 13:57 UTC, mlagally requested changes
The proposed text replaces the reference to XMLSchema, which refers to ISO8601.

The proposed alternative date format reference is to RFC 3339, which is slightly different,
see for a discussion: https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats#:~:text=ISO%208601%20allows%20for%20things,doesn't%20allow%20for%20that.

This has some significant drawbacks, e.g. widely used runtimes use the ISO-8601 format:

https://docs.oracle.com/javase/10/docs/api/java/time/package-summary.html

I think a direct reference to ISO-8601 would be  proper fix - The clarifications on the hour value of 24 and constraints to UTC are useful and should be preserved.

2022-09-28 10:26 UTC, benfrancis commented
Currently the specification has a mix of references to [xmlschema-2](https://www.w3.org/TR/xmlschema-2/), [ISO8601-1](https://www.iso.org/standard/70907.html) and [RFC3339](https://www.rfc-editor.org/rfc/rfc3339).

This PR is intended to consolidate them around a single format for consistency.

As I understand it RFC 3339 is a "profile" of the ISO 8601 standard which adds additional constraints to remove ambiguities (such as not allowing 24 as an hour), which seems appropriate here.

Note that the Thing Description specification [says](https://w3c.github.io/wot-thing-description/#td-basic-types-mapping) that:

> Values that are of type dateTime MUST be serialized as JSON strings following the "date-time" format specified by [[RFC3339](https://w3c.github.io/wot-thing-description/#bib-rfc3339)]

Given that some timestamps which are valid ISO 8601 are not valid under RFC 3339, referencing ISO 8601 is not really enough.

This is a notoriously complicated area and it's also true that there are some timestamps which would be valid under RFC 3339 but not valid under ISO 8601. There's a useful comparison [here](https://github.com/ijmacd/rfc3339-iso8601) and visualisation [here](https://ijmacd.github.io/rfc3339-iso8601/).  As I understand it most programming languages only support a simplified subset of ISO 8601. For example, ECMA262 specifies a [simplified version](https://tc39.es/ecma262/#sec-date-time-string-format) of ISO 8601 which can be parsed by JavaScript, so allowing any ISO 8601 timestamp also unfortunately does not guarantee interoperability.

My suggestion is just to refer to an existing standard rather than invent our own, and being consistent with the Thing Description specification seems like a good idea.

2022-11-04 13:30 UTC, mlagally approved these changes

2022-11-10 11:17 UTC, mlagally commented
Arch call on Nov 10th:
Agree to merge

2022-11-10 11:17 UTC, merged