Adding Common constraints for accessibility
w3c/wot-profile pull request #316
Opened 2022-11-04 12:52 UTC by mlagally

2022-11-04 13:18 UTC, sebastiankb requested changes

2022-11-04 13:18 UTC, sebastiankb commented on index.html
> +	  It is MANDATORY to provide a <code>title</code> that can be automatically rendered in a non-visual way
I think, we should use here the rfc2119 terminology "SHOULD".

2022-11-04 13:18 UTC, sebastiankb commented on index.html
> +	  It is MANDATORY to provide a <code>title</code> that can be automatically rendered in a non-visual way
does this apply to "all" title terms in the TD model or only the top level one?

2022-11-04 15:03 UTC, sebastiankb commented on index.html
> +	  It is MANDATORY to provide a <code>title</code> that can be automatically rendered in a non-visual way
fyi we have already this kind of discussion here: https://github.com/w3c/wot-profile/issues/138

2022-11-09 13:05 UTC, egekorkan commented
I want to record my opinion from the call:
It is not clear where these terms are required. If it is for Thing level, we already need title as required by the TD spec. If it is for all levels, then it would mean having these terms literally everywhere in the TD, including data schemas, which would make TDs explode. The assertions MUST be testable and these are currently not specific enough.

2022-11-09 13:08 UTC, merged