Reference device
w3c/wot-profile pull request #69
Opened 2021-02-18 14:54 UTC by mlagally

2021-02-18 17:01 UTC, sebastiankb requested changes

2021-02-19 07:37 UTC, mlagally commented on index.html
> +	A maximum size of a TD of 16 KB leaves enough headroom and can be still handled on embedded devices with 64-128KB of RAM.
@sebastiankb 
Thanks Sebastian, this makes the discussion much more concrete.
Which size limit would you recommend for TDs produced by this device?

2021-02-19 13:24 UTC, sebastiankb commented on index.html
> +	A maximum size of a TD of 16 KB leaves enough headroom and can be still handled on embedded devices with 64-128KB of RAM.
So far, I see no need for such a restriction in the core profile with HTTP/JSON. But maybe I'm missing something. I would recommend that in the next session we discuss what kind of (realistic) scenarios you need for this constraint. A good orientation can be this figure [here](https://www.w3.org/TR/wot-architecture/#architecture-abstract).

2021-06-23 13:21 UTC, mlagally commented
virtual F2F on 23.6.:
We won't consider use cases where a small device consumes TD.
Close without merging.

2021-06-23 13:21 UTC, closed without merging